version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
