# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
